server:
  port: ${PORT:8084}

spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/middleware
    username: postgres
    password: dwf@sistemas
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: false

management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
    endpoint:
      health:
        show-details: ALWAYS

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://security-server:9999/users/current

---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://middleware.ceoiszqo5pi6.us-east-1.rds.amazonaws.com:5432/middleware
    username: postgres
    password: dwfsistemas
    driver-class-name: org.postgresql.Driver

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://security-server.dwfsistemas:9999/users/current

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8084/info
    healthCheckUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8084/health
    homePageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8084/
    hostname: load-balancer-1235268680.us-east-1.elb.amazonaws.com
    preferIpAddress: false