server:
  port: ${PORT:8085}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true
    
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8085/info
    healthCheckUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8085/health
    homePageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8085/
    hostname: load-balancer-1235268680.us-east-1.elb.amazonaws.com
    preferIpAddress: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS         
