server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}
 
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: false

---
spring:
  profiles: docker

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
 instance:
   preferIpAddress: false
