server:
  port: ${PORT:${SERVER_PORT:0}}

info:
  id: ${spring.application.name}
 
logging:
  level: debug

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true  

---
spring:
  profiles: docker

logging:
  level: debug


eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
 instance:
   preferIpAddress: true  
