server:
  port: ${PORT:8082}
  ssl:
    key-store: classpath:local.pwd.conexao-dwfsistemas.p12
    key-store-password: dwf@sistemas
    keyStoreType: PKCS12
    keyAlias: localhost

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.instance.hostName}:${server.port}/info'
    healthCheckUrl: 'https://${eureka.instance.hostName}:${server.port}/health'
    homePageUrl: 'https://${eureka.instance.hostName}:${server.port}/'
    preferIpAddress: false

management:
  security:
    enabled: false
 
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:9999/users/current

---
spring:
  profiles: docker

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://security-server.dwfsistemas:9999/users/current

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8082/info
    healthCheckUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8082/health
    homePageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8082/
    hostname: load-balancer-1235268680.us-east-1.elb.amazonaws.com
    preferIpAddress: false
