server:
  port: ${PORT:8082}

management:
  security:
    enabled: false
 
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:9999/users/current

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkin-server:9411/