server:
  port: ${PORT:8082}

management:
  security:
    enabled: false
 
   
feign:
  compression:
    request:
      enabled: true
    response:
      enabled: true

      
      
eureka:   
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"  
  endpoint:
    health:
      show-details: ALWAYS
      
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkin-server:9411/

security:
  oauth2:
    resource:
      userInfoUri: http://security-server:9999/users/current        
