server:
  port: ${PORT:8761}
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-alias: eureka-server

  
eureka:
  instance:
    hostname: localhost
    securePort: ${server.port}
    securePortEnabled: true
    nonSecurePortEnabled: false
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
      
---
spring:
  profiles: peer1

server:
  port: 8762
  
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: http://peer2:8763/eureka/  
  
---
spring:
  profiles: peer2

server:
  port: 8763
  
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8762/eureka/  