server:
  port: ${PORT:8761}
  
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://${eureka.instance.hostname}:${server.port}/eureka/
      
---
spring:
  profiles: peer1

server:
  port: 8762
  
eureka:
  instance:
    hostname: peer1
  client:
    serviceUrl:
      defaultZone: https://peer2:8763/eureka/
  
---
spring:
  profiles: peer2

server:
  port: 8763
  
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: https://peer1:8762/eureka/