server:
  port: ${PORT:8081}

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  security:
    enabled: false
 
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: https://localhost:9999/users/current

---
spring:
  profiles: docker

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: https://security-server.dwfsistemas:9999/users/current

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: https://18.214.233.48:8081/info
    healthCheckUrl: https://18.214.233.48:8081/health
    homePageUrl: https://18.214.233.48:8081/
    hostname: 18.214.233.48
    preferIpAddress: false
