server:
  port: ${PORT:8081}

spring:
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/middleware
    username: postgres
    password: dwf@sistemas
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  main:
    banner-mode: log

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
  instance:
    preferIpAddress: false

management:
  security:
    enabled: false
 
security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://localhost:9999/users/current


---
spring:
  profiles: docker
  datasource:
    url: jdbc:postgresql://middleware.ceoiszqo5pi6.us-east-1.rds.amazonaws.com:5432/middleware
    username: postgres
    password: dwfsistemas
    driver-class-name: org.postgresql.Driver

security:
  basic:
    enabled: false
  user:
    password: none
  oauth2:
    resource:
      preferTokenInfo: false
      userInfoUri: http://security-server.dwfsistemas:9999/users/current

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://18.214.233.48:8081/info
    healthCheckUrl: http://18.214.233.48:8081/health
    homePageUrl: http://18.214.233.48:8081/
    hostname: 18.214.233.48
    preferIpAddress: false
