server:
  port: ${PORT:8000}

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
 instance:
   preferIpAddress: true
     
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    crud:
      path: /crud/**
#      url: http://localhost:8082
      serviceId: crud
    compactador:
      path: /compactador/**
#      url: http://localhost:8083
      serviceId: compactador
    contabilizador:
      path: /contabilizador/**
#      url: http://localhost:8090
      serviceId: contabilizador
    server:
      path: /server/**
#      url: http://localhost:8081
      serviceId: server
    admin:
      path: /admin/**
#      url: http://localhost:8084
      serviceId: admin
    security-server:
      path: /security-server/**
#      url: http://localhost:9999
      serviceId: security-server
    zuul-server:
      path: /zuul-server/**
      serviceId: zuul-server
      stripPrefix: false
    eureka-server:
      path: /eureka-server/**
      serviceId: eureka-server
      stripPrefix: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: https://app.conexao-dwfsistemas.com:8000/info
    healthCheckUrl: https://app.conexao-dwfsistemas.com:8000/health
    homePageUrl: https://app.conexao-dwfsistemas.com:8000/
    hostname: app.conexao-dwfsistemas.com
    preferIpAddress: false

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    crud:
      path: /crud/**
      url: https://app.conexao-dwfsistemas.com:8082
#      serviceId: crud
    compactador:
      path: /compactador/**
      url: https://app.conexao-dwfsistemas.com:8083
#      serviceId: compactador
    contabilizador:
      path: /contabilizador/**
      url: https://app.conexao-dwfsistemas.com:8090
#      serviceId: contabilizador
    server:
      path: /server/**
      url: https://18.214.233.48:8081
#      serviceId: server
    admin:
      path: /admin/**
      url: https://app.conexao-dwfsistemas.com:8084
#      serviceId: admin
    security-server:
      path: /security-server/**
      url: https://app.conexao-dwfsistemas.com:9999
#      serviceId: security-server
    zuul-server:
      path: /zuul-server/**
      url: https://app.conexao-dwfsistemas.com:8000
#      serviceId: zuul-server
      stripPrefix: false
    eureka-server:
      path: /eureka-server/**
      url: https://app.conexao-dwfsistemas.com:8761
#      serviceId: eureka-server
      stripPrefix: false
