server:
  port: ${PORT:8000}
    
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    crud:
      path: /crud/**
      url: http://localhost:8082
    compactador:
      path: /compactador/**
      url: http://localhost:8083
    contabilizador:
      path: /contabilizador/**
      url: http://localhost:8090
    server:
      path: /server/**
      url: http://localhost:8081
    admin:
      path: /admin/**
      url: http://localhost:8084
    security-server:
      path: /security-server/**
      url: http://localhost:9999

#ribbon:
#  eureka:
#    enabled: false
      
#aluno-service:
#  ribbon:
#    listOfServers: localhost:8080,localhost:18080
    
#disciplina-service:
#  ribbon:
#    listOfServers: localhost:8081,localhost:18081

---
spring:
  profiles: docker
  zipkin:
    baseUrl: http://zipkin-server:9411/

security:
  oauth2:
    resource:
      userInfoUri: http://security-server:9999/users/current        