server:
  port: ${PORT:8000}
  ssl:
    enabled: true
    key-store: src/main/resources/keystore.p12
    key-store-password: 123456
    key-alias: eureka-server

eureka:
 client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:https://eurekaUser:eurekaPassword@localhost:8761/eureka}
 instance:
   hostname: localhost
   securePort: ${server.port}
   securePortEnabled: true
   nonSecurePortEnabled: false
   preferIpAddress: false
     
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    crud:
      path: /crud/**
      serviceId: crud
    compactador:
      path: /compactador/**
      serviceId: compactador
    contabilizador:
      path: /contabilizador/**
      serviceId: contabilizador
    server:
      path: /server/**
      serviceId: server
    admin:
      path: /admin/**
      serviceId: admin
    security-server:
      path: /security-server/**
      serviceId: security-server
    zuul-server:
      path: /zuul-server/**
      serviceId: zuul-server
      stripPrefix: false
    eureka-server:
      path: /eureka-server/**
      serviceId: eureka-server
      stripPrefix: false

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000

---
spring:
  profiles: docker

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://eurekaUser:eurekaPassword@eureka-server.dwfsistemas:8761/eureka}
  instance:
    statusPageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8000/info
    healthCheckUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8000/health
    homePageUrl: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8000/
    hostname: load-balancer-1235268680.us-east-1.elb.amazonaws.com
    preferIpAddress: false

zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    crud:
      path: /crud/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8082
    compactador:
      path: /compactador/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8083
    contabilizador:
      path: /contabilizador/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8090
    server:
      path: /server/**
      url: http://18.214.233.48:8081
    admin:
      path: /admin/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8084
    security-server:
      path: /security-server/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:9999
    zuul-server:
      path: /zuul-server/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8000
      stripPrefix: false
    eureka-server:
      path: /eureka-server/**
      url: http://load-balancer-1235268680.us-east-1.elb.amazonaws.com:8761
      stripPrefix: false
